version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: